### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: ...==/lib/arm64/libsubstrate.so" has text relocations

### ISSUE THREAD

**Issue by plevart** [gluonhq/substrate#688]
While trying to run a small JavaFX program I made a while back and already successfully ran on substrate on Android, but this time I built and packed it with newest client-maven-plugin 0.1.27 which uses substrate 0.0.25, I get the following error:

```
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] --------- beginning of crash
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500): FATAL EXCEPTION: main
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500): Process: si.pele.rolo.rolo_client, PID: 16500
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/si.pele.rolo.rolo_client-z0y1_5Ve9ta3hxUy6VYXhg==/lib/arm64/libsubstrate.so" has text relocations
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at java.lang.System.loadLibrary(System.java:1669)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:104)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.view.SurfaceView.updateSurface(SurfaceView.java:721)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:148)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2642)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1571)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7615)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1034)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.view.Choreographer.doCallbacks(Choreographer.java:845)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.view.Choreographer.doFrame(Choreographer.java:780)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1020)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.os.Handler.handleCallback(Handler.java:873)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.os.Handler.dispatchMessage(Handler.java:99)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.os.Looper.loop(Looper.java:205)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at android.app.ActivityThread.main(ActivityThread.java:6991)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at java.lang.reflect.Method.invoke(Native Method)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[Thu Jul 02 09:32:23 CEST 2020][INFO] [SUB] E/AndroidRuntime(16500):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:884)
```

**Comment by johanvos** [comment]
Thanks for reporting. This is indeed a recent, known issue. It is being fixed in GraalVM, see https://github.com/oracle/graal/issues/2639 for the issue and the PR that fixes it at https://github.com/oracle/graal/pull/2640
I hope the next dev-build (in a few days) has this fix, and then it should work again.

**Comment by mipastgt** [comment]
I just tried a build with the latest versions of everything
```
GraalVM CE 20.3.0-dev-20200721_0213
client-maven-plugin-0.1.29-20200723.093113-2.jar
substrate-0.0.27-20200723.094030-7.jar
```
https://github.com/gluonhq/client-maven-plugin/issues/211 seems to be fixed now but I immediately stumbled into this issue which still does not seem to be fixed even after three weeks. So again I am not able to produce a working Android app.

**Comment by jperedadnr** [comment]
The underlying issue in GraalVM has just been fixed earlier today: https://github.com/oracle/graal/commit/99386761c13def65d169308dc91d58518ca1c63c

We have to wait for a new 20.3.0-dev version that includes this commit (probably tonight), after which we'll have to integrate this #706 PR.

**Comment by jperedadnr** [comment]
Fixed with #706
